FROM mongo:latest

# Install Node.js
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs

# # Verify installation
RUN mongod --version

# Verify installation
RUN node -v
RUN npm -v

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Expose port 3000
EXPOSE 8080

# Set environment variable for MongoDB URI
ENV MONGODB_URI=mongodb://127.0.0.1:27017/user-tracking

# Copy data import script
COPY resources /docker-entrypoint-initdb.d

# Start MongoDB service and import data
CMD mongod --fork --logpath /var/log/mongodb.log --bind_ip_all && \
    sleep 5 && \
    mongoimport --uri $MONGODB_URI --jsonArray --db user-tracking --collection activities --file /docker-entrypoint-initdb.d/activities.json && \
    mongoimport --uri $MONGODB_URI --jsonArray --db user-tracking --collection suppliers --file /docker-entrypoint-initdb.d/suppliers.json && \
    npm start
